// GENERATED by scripts/upload-images.ts — jangan edit manual
export const IMAGE_URLS: Record<string, string> = {
  "makrab.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VPNz4zljtgr7PzlYQKyaJRCGxVOLdUmBoZWw4h",
  "gantar.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VP5pnhAgynLziQ0TfZpySv1uxoOk23GBJslrad",
  "welpar.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VP9oTGA3poZvbPdqQaxVujLNWtD68GzSUMrygi",
  "bukber.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VPS1uLb1rDXjQ0CYR2qloN85KfH46gm3Lb7wBc",
  "makrab_25.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VPLHkXPPcBNlIroFVktXjcn4mbhaGO9sDWxLw0",
  "gantar_25.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VP3c2ZlawT8m0IJFZrwifxacojsbKpOAHV5dWB",
  "syukwis.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VPp2nDD3TGmGzYjNvn9BFK8eET4LWtIyOfdMDR",
  "penca_oray.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VPzy3RTg2c2g6bUM0NBvaSQKlA19GeoVyDmCtn",
  "penca_oray_1.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VPcOG5mSAFdMHPERga9N3wDU07eCzXhVbTsxtf",
  "penca_oray_2.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VPlmpomXLuxTtIo5OLW0EYd2jQzFpRN6wCAHkn",
  "penca_oray_3.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VP4uWQ4AqMFl2ZKVCn3DAmI0jXgwuLOPYkWq6H",
  "kampung_pulo.jpeg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VPit7YoY0yqWa94ARnkZ0uvix8df3pzrD26j1S",
  "kampung_pulo_1.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VPykDgFslAbzKCPlscxgWIfX4TD6GkEVBN5pno",
  "kampung_pulo_3.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VP0vNuAdjLbzSwZq9TIRNaG6iCBoW87rM2EkDt",
  "burayot.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VPtDJhmD3fu7SOLGyTRiEhkHaBYrZ3cDNwCgjF",
  "burayot_1.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VPhwCFphKlHWjwOCpETs8nvF4xyg23RKLk5Mrq",
  "burayot_2.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VP6rcZ3CkkuTXCSyFPYQsiOzt8cE4mbDMrBqgZ",
  "burayot_3.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VPwG44dpC90xFvud8DHICAi1kBfJMG3neERaLo",
  "pemkab.jpg": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VPSDt3szrDXjQ0CYR2qloN85KfH46gm3Lb7wBc",
  "hero_format.png": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VP7B8oyOvy6GfdzO9ZYvhqCw8XMQgopWb2crkA",
  "hero_tentang_kami.png": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VPkilpAyxETUWv91I0HG7YxL6X8BmueJC2tKOr",
  "maskot.png": "https://zkjtw0mt7b.ufs.sh/f/mQ3sIz52a6VPNeNucxtgr7PzlYQKyaJRCGxVOLdUmBoZWw4h",
};

export function img(name: string) {
  return IMAGE_URLS[name] ?? name;
}
