import { config } from "dotenv";
config({ path: ".env.local" });

import { readFileSync, existsSync, writeFileSync } from "fs";
import { join } from "path";
import { UTApi, UTFile } from "uploadthing/server";
import { db } from "../db/index";
import { kegiatan } from "../db/schema";
import { eq } from "drizzle-orm";

const FILES = [
  "makrab.jpg",
  "gantar.jpg",
  "welpar.jpg",
  "bukber.jpg",
  "makrab_25.jpg",
  "gantar_25.jpg",
  "syukwis.jpg",
  "penca_oray.jpg",
  "penca_oray_1.jpg",
  "penca_oray_2.jpg",
  "penca_oray_3.jpg",
  "kampung_pulo.jpeg",
  "kampung_pulo_1.jpg",
  "kampung_pulo_3.jpg",
  "burayot.jpg",
  "burayot_1.jpg",
  "burayot_2.jpg",
  "burayot_3.jpg",
  "pemkab.jpg",
  "hero_format.png",
  "hero_tentang_kami.png",
  "maskot.png",
];

const MAP_FILE = join(process.cwd(), "lib/images.ts");

function loadExistingMap(): Record<string, string> {
  if (!existsSync(MAP_FILE)) return {};
  const src = readFileSync(MAP_FILE, "utf8");
  const map: Record<string, string> = {};
  const re = /^\s*"(.+?)":\s*"(.+?)",?$/gm;
  for (const m of src.matchAll(re)) {
    map[m[1]] = m[2];
  }
  return map;
}

function writeMapFile(map: Record<string, string>) {
  const body = Object.entries(map)
    .map(([k, v]) => `  "${k}": "${v}",`)
    .join("\n");
  writeFileSync(
    MAP_FILE,
    `// GENERATED by scripts/upload-images.ts — jangan edit manual
export const IMAGE_URLS: Record<string, string> = {
${body}
};

export function img(name: string) {
  return IMAGE_URLS[name] ?? name;
}
`
  );
}

async function main() {
  const utapi = new UTApi();
  const map = loadExistingMap();

  const todo = FILES.filter((f) => {
    const p = join(process.cwd(), "public", f);
    if (!existsSync(p)) {
      console.warn(`SKIP (file tidak ada): ${f}`);
      return false;
    }
    if (map[f]) {
      console.warn(`SKIP (sudah pernah diupload): ${f}`);
      return false;
    }
    return true;
  });

  if (todo.length === 0) {
    console.log("Tidak ada file baru untuk diupload.");
  } else {
    const files = todo.map(
      (name) =>
        new UTFile([readFileSync(join(process.cwd(), "public", name))], name, {
          customId: name,
        })
    );

    const results = await utapi.uploadFiles(files, {
      acl: "public-read",
      concurrency: 5,
    });

    let failed = 0;
    for (const r of results) {
      if (r.error) {
        console.error("GAGAL:", r.error.message);
        failed++;
        continue;
      }
      const data = r.data;
      map[data.customId ?? data.name] = data.ufsUrl;
      console.log("OK:", data.customId ?? data.name, "->", data.ufsUrl);
    }
    if (failed > 0) throw new Error(`${failed} upload gagal`);
  }

  writeMapFile(map);
  console.log(`Map tersimpan di lib/images.ts (${Object.keys(map).length} file)`);

  for (const name of FILES) {
    if (!map[name]) continue;
    await db
      .update(kegiatan)
      .set({ image: map[name] })
      .where(eq(kegiatan.image, name));
  }
  console.log("DB kegiatan.image diperbarui");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
